name: game-demo
version: 0.0.1.0
synopsis: game demo
description: See README at <https://github.com/kayvank/game-demo
author: Your Name
github: kayvank/game-demo
category: Package.Category
license: BSD-3-Clause

dependencies:
  - base >=4.11 && < 5

  - aeson
  - base
  - bmp
  - bytestring
  - containers
  - deepseq
  - file-embed
  - filepath
  - integer-gmp
  - mtl
  - protolude
  - random
  - safe
  - sdl2-mixer
  - tar
  - text
  - time
  - unix
  - unordered-containers
  - vector

  # extra
  - extra
  - monad-extras
  - monad-loops
  - universum

  # formatting
  - ormolu

  # opengl and friends
  - OpenGL
  - JuicyPixels
  - GLFW-b

  # maybe game dev relevant
  - pathfinding

  # music generation
  - Euterpea

default-extensions:
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving # FIXME: Safe Haskell considers GeneralizedNewtypeDeriving unsafe
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
# - PackageImports
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- ViewPatterns

library:
  source-dirs: src

executables:
  spaceminer:
    main: Main.hs
    source-dirs: spaceminer
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: game-demo

ghc-options:
  -Wall

  # -optP-Wno-nonportable-include-path
tests:
  game-demo-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - game-demo
      - hedgehog
